# Completions for 1000+ commands. Under ble.sh use carapace's ble integration:
# the plain bash one fails there with "read: `': not a valid identifier".
if command -v carapace >/dev/null; then
  # shellcheck source=/dev/null  # generated by carapace at shell start
    if [[ ${BLE_VERSION-} ]]; then source <(carapace _carapace bash-ble); else source <(carapace _carapace bash); fi
fi
